[phases.setup]
nixPkgs = ["php", "php81Packages.composer", "mysql"]

[phases.build]
cmds = [
  "composer install" # Install dependencies (if you use Composer)
]

[start]
cmd = "php -S 0.0.0.0:8000 -t hospital" # Change 'hospital' to your actual public directory
